### ISSUE TITLE
Pictures of merchandise

### ISSUE THREAD

**Issue by nilsju** [BandAidCrew/username.github.io#19]

**Comment by SjoenH** [comment]
T-Shirt: https://www.spreadshirt.com/create-your-own?product=1013423837&view=1
Mug: https://www.spreadshirt.com/create-your-own?product=1013423974&view=3
Button: https://www.spreadshirt.com/create-your-own?product=1013423935&view=1
iPhone-case: https://www.spreadshirt.com/create-your-own?product=1013424054&view=1

**Comment by SjoenH** [comment]
Det beste er at dersom du følger linken, så kan du faktisk kjøpe produktet.
